
parameters:
    empty: ''
    scopes: '["profile", "email"]'

services:

    _defaults:
        public: true

    keycloak:
        lazy: true
        class: App\OAuth\Providers\KeycloakProvider
        arguments:
            $httpClient: '@Amp\Http\Client\HttpClient'
            $redirectUri: '%env(OA2T_HTTP_ROOT_URL)%oauth2/callback/keycloak'
            $realmUrl: '%env(default:empty:OA2T_PROVIDERS_KEYCLOAK_REALM_URL)%'
            $clientId: '%env(default:empty:OA2T_PROVIDERS_KEYCLOAK_CLIENT_ID)%'
            $clientSecret: '%env(default:empty:OA2T_PROVIDERS_KEYCLOAK_CLIENT_SECRET)%'
            $scopes: '%env(json:default:scopes:OA2T_PROVIDERS_KEYCLOAK_SCOPES)%'

    yandex:
        lazy: true
        class: App\OAuth\Providers\YandexProvider
        arguments:
            $httpClient: '@Amp\Http\Client\HttpClient'
            $redirectUri: '%env(OA2T_HTTP_ROOT_URL)%oauth2/callback/yandex'
            $clientId: '%env(default:empty:OA2T_PROVIDERS_YANDEX_CLIENT_ID)%'
            $clientSecret: '%env(default:empty:OA2T_PROVIDERS_YANDEX_CLIENT_SECRET)%'


#    google:
#        class: App\OAuth\Providers\GenericProvider
#        arguments:
#            $httpClient: '@Amp\Http\Client\HttpClient'
#            $redirectUri: '%env(OA2T_HTTP_ROOT_URL)%oauth2/callback/google'
#            $authorizationUrl: ''
#            $accessTokenUrl: ''
#            $clientId: '%env(default:empty:OA2T_PROVIDERS_GOOGLE_CLIENT_ID)%'
#            $clientSecret: '%env(default:empty:OA2T_PROVIDERS_GOOGLE_CLIENT_SECRET)%'
#            $name: 'Google'
