imports:
    - { resource: providers.yaml }

parameters:
    env(OA2T_HTTP_ADDRESS): 0.0.0.0:8088
    env(OA2T_HTTP_ROOT_URL): http://0.0.0.0:8088/
    env(OA2T_UPSTREAM): http://127.0.0.0:80/
    env(OA2T_EMAIL_DOMAINS): '*'
    env(OA2T_COOKIE_SECRET): b1677dfde85309b4b99e72bc4f547442
    env(OA2T_COOKIE_SECURE): 'true'
    env(OA2T_COOKIE_EXPIRE): PT24H
    env(OA2T_PROVIDERS): '["yandex", "google"]'
    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Psr\Log\LoggerInterface: '@logger'
#            Amp\Http\Client\HttpClient: '@Amp\Http\Client\HttpClient'

    logger:
        synthetic: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\Services\:
#        resource: '../src/Services/*'
#        exclude: '../src/Services/{DependencyInjection,Entity,Tests,Kernel.php}'
#        public: true
#

    App\Handlers\:
        resource: '../src/Handlers/*'
        exclude: '../src/Handlers/views'
        public: true

    App\OAuth\:
        resource: '../src/OAuth/*'
        exclude: '../src/OAuth/Providers'
        public: true

    App\Symfony\:
        resource: '../src/Symfony/*'
        public: true

    App\Config:
        class: App\Config
        public: true
        properties:
            httpAddress: '%env(OA2T_HTTP_ADDRESS)%'
            httpRootUrl: '%env(OA2T_HTTP_ROOT_URL)%'
            upstream: '%env(OA2T_UPSTREAM)%'
            emailDomains: '%env(OA2T_EMAIL_DOMAINS)%'
            cookieSecret: '%env(OA2T_COOKIE_SECRET)%'
            cookieSecure: '%env(bool:OA2T_COOKIE_SECURE)%'
            cookieExpire: '%env(OA2T_COOKIE_EXPIRE)%'
            providers: '%env(json:OA2T_PROVIDERS)%'
#            providers: '%env(graph:OA2T_PROVIDERS)%'
            
    App\Application:
        class: App\Application
        public: true

    App\OAuth\Identity:
        class: App\OAuth\Identity
        autowire: false

    App\OAuth\IdentityLoader:
        class: App\OAuth\IdentityLoader
        autowire: false

    Amp\Http\Client\HttpClientBuilder:
        class: Amp\Http\Client\HttpClientBuilder
        public: true
        calls:
          - retry: !returns_clone [0]
          - skipDefaultUserAgent: !returns_clone []
          - usingPool: !returns_clone ['@proxy_connection_limit_pool']

    proxy_connection_limit_pool:
        class: Amp\Http\Client\Connection\ConnectionLimitingPool
        factory: [null, 'byAuthority']
        arguments:
            $connectionLimit: 5
            $connectionFactory: '@proxy_default_connection_factory'

# without connect retries
    proxy_default_connection_factory:
        class: Amp\Http\Client\Connection\DefaultConnectionFactory
        arguments:
            $connector: '@Amp\Socket\DnsSocketConnector'

    Amp\Socket\DnsSocketConnector:
        class: Amp\Socket\DnsSocketConnector

    Amp\Http\Client\HttpClient:
        class: Amp\Http\Client\HttpClient
        public: true
        factory: [ '@Amp\Http\Client\HttpClientBuilder', 'build' ]
        
    Amp\Http\Cookie\CookieAttributes:
        class: Amp\Http\Cookie\CookieAttributes
        public: true
        factory: [null, 'default']
        calls:
          - withPath: !returns_clone ['/']

