imports:
    - { resource: providers*.yaml }

parameters:
    env(OA2T_HTTP_ADDRESS): 0.0.0.0:8088
    env(OA2T_HTTP_ROOT_URL): http://0.0.0.0:8088/
    env(OA2T_UPSTREAM): http://127.0.0.0:80/
    env(OA2T_EMAIL_DOMAINS): '*'
    env(OA2T_COOKIE_SECURE): 'true'
    env(OA2T_COOKIE_EXPIRE): PT24H
    env(OA2T_PROVIDERS): '["yandex", "google"]'
    env(OA2T_TRUSTED_FORWARDERS): ''
    env(OA2T_ACCESS_LOG): './access.log'
    env(OA2T_APP_LOG): 'php://stdout'
    

services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Psr\Log\LoggerInterface: '@logger'
#            Amp\Http\Client\HttpClient: '@Amp\Http\Client\HttpClient'

    logger:
        synthetic: true

    App\Handlers\:
        resource: '../src/Handlers/*'
        exclude: '../src/Handlers/views'

    App\OAuth\:
        resource: '../src/OAuth/*'
        exclude: '../src/OAuth/Providers'

    App\Symfony\:
        resource: '../src/Symfony/*'

    App\Config:
        class: App\Config
        properties:
            httpAddress: '%env(OA2T_HTTP_ADDRESS)%'
            httpRootUrl: '%env(OA2T_HTTP_ROOT_URL)%'
            postLoginUrl: '%env(OA2T_POST_LOGIN_URL)%'
            upstream: '%env(OA2T_UPSTREAM)%'
            emailDomains: '%env(OA2T_EMAIL_DOMAINS)%'
            emailsAllowed: '%env(OA2T_EMAILS_ALLOWED)%'
            cookieExpire: '%env(OA2T_COOKIE_EXPIRE)%'
            cookieSecure: '%env(bool:OA2T_COOKIE_SECURE)%'
            providers: '%env(json:OA2T_PROVIDERS)%'
            trustedForwarders: '%env(OA2T_TRUSTED_FORWARDERS)%'
            accessLog: '%env(OA2T_ACCESS_LOG)%'
            appLog: '%env(OA2T_APP_LOG)%'
            
    App\Application:
        class: App\Application
            
    App\AccessControl:
        class: App\AccessControl

    App\OAuth\Identity:
        class: App\OAuth\Identity
        autowire: false

    App\OAuth\IdentityLoader:
        class: App\OAuth\IdentityLoader
        autowire: false

    Amp\Http\Client\HttpClientBuilder:
        class: Amp\Http\Client\HttpClientBuilder
        calls:
          - retry: !returns_clone [0]
          - skipDefaultUserAgent: !returns_clone []
          - usingPool: !returns_clone ['@proxy_connection_limit_pool']

    proxy_connection_limit_pool:
        class: Amp\Http\Client\Connection\ConnectionLimitingPool
        factory: [null, 'byAuthority']
        arguments:
            $connectionLimit: 5
            $connectionFactory: '@proxy_default_connection_factory'

# without connect retries
    proxy_default_connection_factory:
        class: Amp\Http\Client\Connection\DefaultConnectionFactory
        arguments:
            $connector: '@Amp\Socket\DnsSocketConnector'

    Amp\Socket\DnsSocketConnector:
        class: Amp\Socket\DnsSocketConnector

    Amp\Http\Client\HttpClient:
        class: Amp\Http\Client\HttpClient
        factory: [ '@Amp\Http\Client\HttpClientBuilder', 'build' ]
        
    Amp\Http\Server\Session\SessionFactory:
        class: Amp\Http\Server\Session\SessionFactory
        arguments:
            $storage: '@session_storage'
        
    session_storage:
        class: Amp\Http\Server\Session\LocalSessionStorage
        arguments:
            $sessionLifetime: '@=service("App\\Config").getCookieMaxAge()'
        
